/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 50 -o first/LIA/norm-L_Accu_first -m /usr/local/fsl/data/first/models_336_bin/L_Accu_bin.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-L_Accu_first -o first/LIA/norm-L_Accu_corr -i norm -b fast
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 50 -o first/LIA/norm-L_Amyg_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/L_Amyg.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-L_Amyg_first -o first/LIA/norm-L_Amyg_corr -i norm -b fast
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 30 -o first/LIA/norm-L_Caud_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/L_Caud.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-L_Caud_first -o first/LIA/norm-L_Caud_corr -i norm -b fast
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 30 -o first/LIA/norm-L_Hipp_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/L_Hipp.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-L_Hipp_first -o first/LIA/norm-L_Hipp_corr -i norm -b fast
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 40 -o first/LIA/norm-L_Pall_first -m /usr/local/fsl/data/first/models_336_bin/05mm/L_Pall_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-L_Pall_first -o first/LIA/norm-L_Pall_corr -i norm -b none
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 40 -o first/LIA/norm-L_Puta_first -m /usr/local/fsl/data/first/models_336_bin/05mm/L_Puta_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-L_Puta_first -o first/LIA/norm-L_Puta_corr -i norm -b none
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 40 -o first/LIA/norm-L_Thal_first -m /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-L_Thal_first -o first/LIA/norm-L_Thal_corr -i norm -b none
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 50 -o first/LIA/norm-R_Accu_first -m /usr/local/fsl/data/first/models_336_bin/R_Accu_bin.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-R_Accu_first -o first/LIA/norm-R_Accu_corr -i norm -b fast
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 50 -o first/LIA/norm-R_Amyg_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/R_Amyg.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-R_Amyg_first -o first/LIA/norm-R_Amyg_corr -i norm -b fast
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 30 -o first/LIA/norm-R_Caud_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/R_Caud.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-R_Caud_first -o first/LIA/norm-R_Caud_corr -i norm -b fast
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 30 -o first/LIA/norm-R_Hipp_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/R_Hipp.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-R_Hipp_first -o first/LIA/norm-R_Hipp_corr -i norm -b fast
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 40 -o first/LIA/norm-R_Pall_first -m /usr/local/fsl/data/first/models_336_bin/05mm/R_Pall_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-R_Pall_first -o first/LIA/norm-R_Pall_corr -i norm -b none
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 40 -o first/LIA/norm-R_Puta_first -m /usr/local/fsl/data/first/models_336_bin/05mm/R_Puta_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-R_Puta_first -o first/LIA/norm-R_Puta_corr -i norm -b none
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 40 -o first/LIA/norm-R_Thal_first -m /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-R_Thal_first -o first/LIA/norm-R_Thal_corr -i norm -b none
/usr/local/fsl/bin/run_first -i norm -t norm_to_std_sub.mat -n 40 -o first/LIA/norm-BrStem_first -m /usr/local/fsl/data/first/models_336_bin/BrStem_bin.bmv; /usr/local/fsl/bin/first_boundary_corr -s first/LIA/norm-BrStem_first -o first/LIA/norm-BrStem_corr -i norm -b fast
