/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 50 -o ../freesurfer/first/-L_Accu_first -m /usr/local/fsl//data/first/models_336_bin/L_Accu_bin.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-L_Accu_first -o ../freesurfer/first/-L_Accu_corr -i ../processed/sub-01/anat/sub-01_T1w -b fast
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 50 -o ../freesurfer/first/-L_Amyg_first -m /usr/local/fsl//data/first/models_336_bin/intref_thal/L_Amyg.bmv -intref /usr/local/fsl//data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-L_Amyg_first -o ../freesurfer/first/-L_Amyg_corr -i ../processed/sub-01/anat/sub-01_T1w -b fast
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 30 -o ../freesurfer/first/-L_Caud_first -m /usr/local/fsl//data/first/models_336_bin/intref_thal/L_Caud.bmv -intref /usr/local/fsl//data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-L_Caud_first -o ../freesurfer/first/-L_Caud_corr -i ../processed/sub-01/anat/sub-01_T1w -b fast
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 30 -o ../freesurfer/first/-L_Hipp_first -m /usr/local/fsl//data/first/models_336_bin/intref_thal/L_Hipp.bmv -intref /usr/local/fsl//data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-L_Hipp_first -o ../freesurfer/first/-L_Hipp_corr -i ../processed/sub-01/anat/sub-01_T1w -b fast
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 40 -o ../freesurfer/first/-L_Pall_first -m /usr/local/fsl//data/first/models_336_bin/05mm/L_Pall_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-L_Pall_first -o ../freesurfer/first/-L_Pall_corr -i ../processed/sub-01/anat/sub-01_T1w -b none
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 40 -o ../freesurfer/first/-L_Puta_first -m /usr/local/fsl//data/first/models_336_bin/05mm/L_Puta_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-L_Puta_first -o ../freesurfer/first/-L_Puta_corr -i ../processed/sub-01/anat/sub-01_T1w -b none
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 40 -o ../freesurfer/first/-L_Thal_first -m /usr/local/fsl//data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-L_Thal_first -o ../freesurfer/first/-L_Thal_corr -i ../processed/sub-01/anat/sub-01_T1w -b none
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 50 -o ../freesurfer/first/-R_Accu_first -m /usr/local/fsl//data/first/models_336_bin/R_Accu_bin.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-R_Accu_first -o ../freesurfer/first/-R_Accu_corr -i ../processed/sub-01/anat/sub-01_T1w -b fast
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 50 -o ../freesurfer/first/-R_Amyg_first -m /usr/local/fsl//data/first/models_336_bin/intref_thal/R_Amyg.bmv -intref /usr/local/fsl//data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-R_Amyg_first -o ../freesurfer/first/-R_Amyg_corr -i ../processed/sub-01/anat/sub-01_T1w -b fast
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 30 -o ../freesurfer/first/-R_Caud_first -m /usr/local/fsl//data/first/models_336_bin/intref_thal/R_Caud.bmv -intref /usr/local/fsl//data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-R_Caud_first -o ../freesurfer/first/-R_Caud_corr -i ../processed/sub-01/anat/sub-01_T1w -b fast
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 30 -o ../freesurfer/first/-R_Hipp_first -m /usr/local/fsl//data/first/models_336_bin/intref_thal/R_Hipp.bmv -intref /usr/local/fsl//data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-R_Hipp_first -o ../freesurfer/first/-R_Hipp_corr -i ../processed/sub-01/anat/sub-01_T1w -b fast
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 40 -o ../freesurfer/first/-R_Pall_first -m /usr/local/fsl//data/first/models_336_bin/05mm/R_Pall_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-R_Pall_first -o ../freesurfer/first/-R_Pall_corr -i ../processed/sub-01/anat/sub-01_T1w -b none
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 40 -o ../freesurfer/first/-R_Puta_first -m /usr/local/fsl//data/first/models_336_bin/05mm/R_Puta_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-R_Puta_first -o ../freesurfer/first/-R_Puta_corr -i ../processed/sub-01/anat/sub-01_T1w -b none
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 40 -o ../freesurfer/first/-R_Thal_first -m /usr/local/fsl//data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-R_Thal_first -o ../freesurfer/first/-R_Thal_corr -i ../processed/sub-01/anat/sub-01_T1w -b none
/usr/local/fsl//bin/run_first -i ../processed/sub-01/anat/sub-01_T1w -t ../processed/sub-01/anat/sub-01_T1w_to_std_sub.mat -n 40 -o ../freesurfer/first/-BrStem_first -m /usr/local/fsl//data/first/models_336_bin/BrStem_bin.bmv; /usr/local/fsl//bin/first_boundary_corr -s ../freesurfer/first/-BrStem_first -o ../freesurfer/first/-BrStem_corr -i ../processed/sub-01/anat/sub-01_T1w -b fast
